# Inventory Demand
picking_demand_dict1 = dict({
    'server': 'HOST',
    'program': 'WAMAS',
    'serial_number': 1,
    'creation_time': '20201024193053',
    'record_type': 'LOGIMATPD00004',
    'client_id': 'DEFAULT',
    'picking_demand_id': '',
    'external_reference': '',
    'priority': 1,
    'note_number': '',
    'delivery_time': '',
    'picking_demand_time': '',
    'info': '',
    'info2': '',
    'partner': '',
    'title': '',
    'name': '',
    'name2': '',
    'name3': '',
    'name4': '',
    'street': '',
    'city': '',
    'district': '',
    'region': '',
    'country': '',
    'zip_code': '',
    'phone': '',
    'fax': '',
    'email': '',
    'website': '',
    'gln': '',
    'language': '',
    'time_zone': '',
    'logimat_zone': ''
})

# Inventory Demand
picking_demand_dict2 = dict({
    'host': 'HOST',
    'program': 'WAMAS',
    'serial_number': 1,
    'creation_time': '20201024193053',
    'record_type': 'LOGIMATPDL00003',
    'picking_demand_id': '',
    'system_partner_line': '',
    'item_number': '',
    'item_variant': '',
    'item_batch': '',
    'prod_table': '',
    'bbd': '',
    'ordered_quantity': '',
    'csia_1': ''# Its a group of 20 items[]
})